### ISSUE TITLE
MOI wrapper and JuMP v0.19

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/Alpine.jl#101]
Remove MPB dependency and move to an MOI interface. This also drops support for Julia 0.6 and 0.7 completely.

**Comment by kaarthiksundar** [comment]
Other feature list:

1. SCIP support with SCIP’s MOI interface. 
2. Logging using Memento.jl
3. Solver support clean up. 
4. Error when model has unbounded variables. 
5. Explicitly drop support for integer and support only binary variables.

**Comment by harshangrjn** [comment]
Since #97 was closed, adding this here. Alpine currently throws error with Gurobi as the mip_solver. This also needs to be fixed.

**Comment by kaarthiksundar** [comment]
@harshangrjn fyi, this is not going to get released in the near future; I see this getting done end of the calendar year. I am first working on doing this update for Juniper.jl to figure out MOI. Also this update will work only when other solvers are updated to use MOI, for instance Bonmin does not work with the new MOI now and no MINLP local solvers do (hence the push for Juniper.jl so that I can test Alpine.jl with Juniper.jl). Also, feel free to add to the list if any other long-term issues need to be fixed in this update. Meanwhile short-term issues that need to be fixed in the current version of Alpine can be posted as separate issues.

**Comment by harshangrjn** [comment]
@kaarthiksundar The reason #97 issue was brought back here was because it was closed without solving the Gurobi issue in it. Before closing issues, its probably better to ensure separate new issues are created if there are multiple ones in the same thread, just so that they are not lost.

**Comment by krishpat** [comment]
Supporting Alpine with Gurobi as the mip_solver will be helpful as Gurobi seems to do better on MIQCPs compared to CPLEX, assuming MIQCPs are in every iteration of the algorithm.

**Comment by kaarthiksundar** [comment]
@krishpat @harshangrjn Please try using Gurobi in the master branch. It should work now.

**Comment by harshangrjn** [comment]
@kaarthiksundar Thanks!
