### ISSUE TITLE
Slow run times for polynomial minimization 

### ISSUE THREAD

**Issue by krishpat** [lanl-ansi/Alpine.jl#105]
When I run this simple problem of minimizing a bivariate polynomial on a laptop, 
```
m = Model(solver=AlpineSolver(nlp_solver = IpoptSolver(), mip_solver = CplexSolver()))
@variable(m, -1 <= x[1:2] <= 1)
@NLobjective(m, Min, x[1]^2 - 2*x[1]^4 + x[1]*x[2] - 4*x[2]^2 + 4*x[2]^8)
solve(m)
```

Alpine gets stuck in Iteration-2 and doesn't converge even after ~1000s. Also, Alpine displays the following stats about the problem: 
```
 Term BILINEAR Count = 1 
 Term MONOMIAL Count = 2 
 Term MULTILINEAR Count = 2 
```

1. Why is Alpine recognizing 2 multilinear terms when there are no multilinears in this problem? Are x[1]^4 and x[2]^8 recognized as multilinears? 
2. Is there any parameter to play with to improve the run times? For a 2 variable NLP, these run times seem very slow compared to SCIP which solves this NLP in ~15s. 

Thank you!

**Comment by harshangrjn** [comment]
@krishpat, This is a good example. 

1. Internally, by default, the way Alpine is currently handling higher-order monomials (x^4, x^8) is by lifting x^8 to y1.y2.y3.y4 such that y_i=x^2 i=1,..,4 and treating y1.y2.y3.y4 as a multilinear term. Hence, Alpine is reporting 2 multilinears, each for x^4 and x^8. We are currently working on fixing this reformulation, which can improve rum-times drastically as shown below. 

2. To improve your run-time, you just have to encode your objective in the following form. 
```
@NLobjective(m, Min, x[1]^2 - 2*(x[1]^2)*(x[1]^2) + x[1]*x[2] - 4*x[2]^2 + 4*(x[2]^2*x[2]^2)*(x[2]^2*x[2]^2))
```
In this case, Alpine does not treat higher-order monomials as multilinears and converges to the global optimum in 2 iterations (~5s) on my laptop (faster than SCIP :-)). Here are the iterations: 
```
 | NLP           | MIP           || Objective     | Bound         | GAP (%)       | CLOCK         | | Iter   
 | 0.0           | -3.6934       || 0.0           | -3.6934       | LARGE         | 5.76s         | | 1
 | -3.6934       | -3.6934       || -3.6934       | -3.6934       | 0.0           | 5.76s         | | finish
```

That said, there are numerous parameters (in solver.jl) you can modify to improve runtimes of Alpine. Particularly, this parameter can be varaied in integer values (>=3) https://github.com/lanl-ansi/Alpine.jl/blob/db92712ed9fb35854f6679e33d82fa32ddcbb028/src/solver.jl#L31

**Comment by harshangrjn** [comment]
Let me know if this addresses your issue and I shall close this.

**Comment by krishpat** [comment]
@harshangrjn Run time improvements are amazing. Thanks for addressing this issue. Will be good to have this reformulation default in Alpine and also have this documented somewhere.

**Comment by harshangrjn** [comment]
@krishpat Agreed! We are working on it.
