### ISSUE TITLE
Error messages for unsupported functions 

### ISSUE THREAD

**Issue by krishpat** [lanl-ansi/Alpine.jl#106]
Consider this NLP
```
m = Model(solver=AlpineSolver(nlp_solver = IpoptSolver(print_level=0), mip_solver = CplexSolver(CPX_PARAM_SCRIND=0)))
@variable(m, 0.1 <= x[1:2] <= 2)
@NLobjective(m, Min, x[1]*x[2] + F)
solve(m)
```
1. When F = log(x[1]),  Alpine displays `ERROR: LoadError: Unkown/unspported operator log` before Ipopt is invoked. 

2. When F = sin(x[1]), Alpine invokes Ipopt to obtain a local point and then displays `ERROR: LoadError: Integer features are OFF. No support for INTLIN at this condition.` Not sure why Ipopt was invoked and what this error message means. 

3. When F = x[1]/x[2], Alpine displays `ERROR: LoadError: UndefVarError: x not defined` before Ipopt is invoked. 

Error messages in cases 2 & 3 do not seem to be related to the unsupported functions. Message similar to case 1 for all unsupported functions will be more useful.

**Comment by harshangrjn** [comment]
These issues have been fixed. Pull the master branch and you will see consistent error messages. In your case, messages are:
1. `ERROR: LoadError: Alpine does not currently support log operator acting on a variable`
2. `ERROR: LoadError: Alpine does not currently support sin operator acting on a variable`
3. `ERROR: LoadError: Alpine does not currently support / operator with a variable in the denominator`

If this addresses your issue, I shall close this thread.

**Comment by krishpat** [comment]
@harshangrjn Thanks for addressing these issues. I see another issue now. When F = x[1]^1, Alpine displays this error: `ERROR: LoadError: Alpine currently supports `^` operator with only positive integer exponents`

Look like Alpine is not recognizing and replacing x[1]^1 with x[1].

**Comment by harshangrjn** [comment]
@krishpat F = x[1]^1 case has been fixed. You can update Alpine since the new version has been released. Or you can even pull the master branch. 

Thanks to @kaarthiksundar for the help!

**Comment by krishpat** [comment]
@harshangrjn Thanks for the fix. Alpine's log looks very neat now. 👍
