### ISSUE TITLE
Compatible with JuMP v0.19

### ISSUE THREAD

**Issue by waynelapierre** [lanl-ansi/Alpine.jl#111]
When will Alpine work with JuMP 0.19?

**Comment by kaarthiksundar** [comment]
Work is in progress. It might take a few more months. The transition is in the branch entitled moi-wrapper

**Comment by kaarthiksundar** [comment]
https://github.com/lanl-ansi/Alpine.jl/issues/101

**Comment by waynelapierre** [comment]
How about the time line of Juniper?

**Comment by kaarthiksundar** [comment]
Juniper will be released in two weeks time.

**Comment by waynelapierre** [comment]
Does the new Juniper support user defined functions?

**Comment by kaarthiksundar** [comment]
Can you be more specific. What do you mean by user defined function? Can you also post juniper related functions in Juniper.jl. cc: @Wikunia @ccoffrin

**Comment by waynelapierre** [comment]
I mean if I have a complicated nonlinear objective function, and my parameters are purely integers, can Juniper optimize such issues?

**Comment by kaarthiksundar** [comment]
Yes, it can. If there is a specific problem that is of interest and does not work, you can post it as an issue in Juniper.jl.

**Comment by kaarthiksundar** [comment]
https://github.com/lanl-ansi/Alpine.jl/issues/101
