### ISSUE TITLE
On variables chosen for partitioning

### ISSUE THREAD

**Issue by krishpat** [lanl-ansi/Alpine.jl#121]
In this [paper](https://harshangrjn.github.io/pdf/JOGO_2018.pdf) (linked in the references) I was observing that the piecewise formulation presented is to partition both the variables in a given bilinear term. Does Alpine always partition every variable in a bilinear term? If so, doesn't it slow down runtimes since a lot of binary variables are added to the formulation?

**Comment by harshangrjn** [comment]
https://github.com/lanl-ansi/Alpine.jl/blob/b1970048e90a1f1e72c54ddbbd40028a735af6d8/src/solver.jl#L33

@krishpat, Alpine supports both bivariate and univariate partitioning, which can be controlled using the input parameter "disc_var_pick" (in the above link). "0" implies all variable partitioning involved in the bilinear terms and "1" implies univariate partitioning. In the latter case, univariate is chosen using a min. vertex cover (MVC) algorithm. For example, if the bilinear terms in an NLP are `x1*x2, x2*x3, x2*x4, x4*x5`, MVC of this expression-interaction-graph contains `x2` and `x4`, which are chosen for partitioning. 

Hope this helps!

**Comment by krishpat** [comment]
@harshangrjn Thanks for the clarification!! In that case, why would Alpine even choose to do bivariate partitioning if it makes the global convergence harder? Is the default way of solving in Alpine using the MVC algorithm you mentioned?

**Comment by harshangrjn** [comment]
@krishpat That is a good question. Bivariate partitioning, though as you mentioned makes the global convergence harder, it is not necessarily what we observe on smaller NLPs. Bivariate partitioning can tighten the piecewise relaxations much faster and close the optimality gap faster too. Here is a simple NLP which should explain this better: https://github.com/lanl-ansi/MINLPLib.jl/blob/master/instances/special/nlp3.jl  

### Univariate partitioning
If you solve above NLP using Alpine with `disc_var_pick=1`, which is going to partition only `x1,x2` and `x3` variables, here are the lower bounding iterations of Alpine (with presolve on) 
```
====================================================================================================
LOWER-BOUNDING ITERATIONS 

| Iter   | Incumbent       | Best Incumbent      | Lower Bound        | Gap (%)         | Time      
| 1      | 7049.2479       | 7049.2479           | 3596.6955          | 48.9776         | 0.39s            
| 2      | 7112.2653       | 7049.2479           | 4289.5621          | 39.14866        | 0.43s            
| 3      | -               | 7049.2479           | 4934.3676          | 30.0015         | 0.49s            
| 4      | -               | 7049.2479           | 5619.9843          | 20.27541        | 0.58s            
| 5      | 7222.8738       | 7049.2479           | 5849.7172          | 17.01644        | 0.66s            
| 6      | -               | 7049.2479           | 5933.2429          | 15.83155        | 0.76s            
| 7      | -               | 7049.2479           | 6165.3318          | 12.53915        | 0.92s            
| 8      | 7142.429        | 7049.2479           | 6434.1256          | 8.72607         | 1.02s            
| 9      | -               | 7049.2479           | 6511.1201          | 7.63383         | 1.21s            
| 10     | -               | 7049.2479           | 6535.2444          | 7.29161         | 1.41s            
| 11     | 7059.4722       | 7049.2479           | 6616.3328          | 6.14129         | 1.65s            
| 12     | -               | 7049.2479           | 6697.349           | 4.99201         | 2.12s            
| 13     | -               | 7049.2479           | 6704.722           | 4.88741         | 2.53s            
| 14     | 7056.9019       | 7049.2479           | 6769.8427          | 3.96362         | 3.23s            
| 15     | -               | 7049.2479           | 6798.4388          | 3.55796         | 4.14s            
| 16     | 7079.172        | 7049.2479           | 6864.6988          | 2.618           | 5.05s            
| 17     | 7091.1925       | 7049.2479           | 6876.6951          | 2.44782         | 6.32s            
| 18     | -               | 7049.2479           | 6896.4424          | 2.16769         | 9.07s            
| 19     | 7082.7949       | 7049.2479           | 6915.8008          | 1.89307         | 12.5s            
| 20     | -               | 7049.2479           | 6918.5033          | 1.85473         | 16.05s           
| 21     | -               | 7049.2479           | 6934.8247          | 1.6232          | 19.97s           
| 22     | -               | 7049.2479           | 6938.4735          | 1.57144         | 24.45s           
| 23     | -               | 7049.2479           | 6939.9485          | 1.55051         | 38.17s           
| 24     | -               | 7049.2479           | 6943.7389          | 1.49674         | 48.56s           
| 25     | 7073.6886       | 7049.2479           | 6951.3001          | 1.38948         | 62.4s            
| 26     | -               | 7049.2479           | 6956.3             | 1.31855         | 73.02s           
| 27     | -               | 7049.2479           | 6964.6064          | 1.20072         | 82.92s           
| 28     | 7077.9114       | 7049.2479           | 6969.4743          | 1.13166         | 100.87s          
| 29     | -               | 7049.2479           | 6976.2301          | 1.03582         | 121.38s          
| 30     | -               | 7049.2479           | 6979.5655          | 0.98851         | 140.49s          
| 31     | -               | 7049.2479           | 6980.7974          | 0.97103         | 153.87s          
| 32     | -               | 7049.2479           | 6982.2504          | 0.95042         | 181.27s          
| 33     | -               | 7049.2479           | 6987.518           | 0.87569         | 206.15s          
| 34     | -               | 7049.2479           | 6989.6405          | 0.84559         | 225.12s          
| 35     | -               | 7049.2479           | 6990.6806          | 0.83083         | 244.21s          
| 36     | -               | 7049.2479           | 6993.2622          | 0.79421         | 267.6s           
| 37     | 7051.0898       | 7049.2479           | 6997.6352          | 0.73217         | 312.66s     
```
### Bivariate partitioning
If you solve the same NLP using Alpine with `disc_var_pick=0`, which is going to partition only `x1` through `x8` variables, here are the lower bounding iterations of Alpine (with presolve on) 
```
====================================================================================================
LOWER-BOUNDING ITERATIONS 

| Iter   | Incumbent       | Best Incumbent      | Lower Bound        | Gap (%)         | Time      
| 1      | 7049.2479       | 7049.2479           | 4660.1641          | 33.89133        | 0.44s            
| 2      | 7419.3304       | 7049.2479           | 6708.3492          | 4.83596         | 0.51s            
| 3      | 7049.2479       | 7049.2479           | 6979.1607          | 0.99425         | 0.72s            
| 4      | 7052.7314       | 7049.2479           | 7024.466           | 0.35155         | 1.21s            
| 5      | 7049.542        | 7049.2479           | 7046.578           | 0.03787         | 1.97s            
| 6      | 7049.3754       | 7049.2479           | 7047.9301          | 0.01869         | 4.46s            
| finish | 7049.2554       | 7049.2479           | 7048.9848          | 0.00373         | 8.08s            
====================================================================================================
```
As you can observe, the run times of bivariate partitioning is much faster and also converges to the global optimum in contrast to the univariate partitioning which ends up adding lesser number of binary variables per iteration but eventually many binaries due to the number of iterations. Hence, Alpine switches the default between these two partitioning methods depending on the size of the NLP.

**Comment by krishpat** [comment]
@harshangrjn It is really amazing to see the improvement in run times by applying a counter-intuitive-type method of bivariate partitioning. I quickly tested on other small NLPs and Alpine's bivariate partitioning seems to be quite efficient. 

Thanks again for the detailed clarification. Looks like I need to understand in detail all the user input parameters.

**Comment by harshangrjn** [comment]
We need to write a detailed user manual, explaining all these parameters. We hope to get to this soon.

**Comment by harshangrjn** [comment]
Closing this since this is related to solver documentation!
