### ISSUE TITLE
Precompiling Issue

### ISSUE THREAD

**Issue by asavasci** [lanl-ansi/Alpine.jl#136]
I am new to Alpine, having issues with precompile stage as follows

[ Info: Precompiling Alpine [07493b3f-dabb-5b16-a503-4139292d7dd4]
ERROR: LoadError: LoadError: UndefVarError: Variable not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1044
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /Users/alpersavasci/.julia/packages/Alpine/k3g7z/src/Alpine.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1044
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:393
 [14] top-level scope at ./none:3
in expression starting at /Users/alpersavasci/.julia/packages/Alpine/k3g7z/src/tmc.jl:203
in expression starting at /Users/alpersavasci/.julia/packages/Alpine/k3g7z/src/Alpine.jl:57
ERROR: LoadError: Failed to precompile Alpine [07493b3f-dabb-5b16-a503-4139292d7dd4] to /Users/alpersavasci/.julia/compiled/v1.0/Alpine/TRSJF.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [2] _require(::Base.PkgId) at ./loading.jl:960
 [3] require(::Base.PkgId) at ./loading.jl:858
 [4] require(::Module, ::Symbol) at ./loading.jl:853
in expression starting at 

how can we resolve it?

**Comment by harshangrjn** [comment]
Alpine currently works only with JuMP <= v0.18.5. That may be the reason why you see this bug. Let me know if this fixes your issue.

**Comment by asavasci** [comment]
Yes, older version works with Alpine. 
Now, I am getting different error regarding LinearQuadraticModel as follows 

LoadError: MethodError: no method matching LinearQuadraticModel(::AlpineSolver)
Closest candidates are:
  LinearQuadraticModel(!Matched::ECOSSolver) at C:\Users\alper\.julia\packages\ECOS\pP33Q\src\MPB_wrapper.jl:81
  LinearQuadraticModel(!Matched::GurobiSolver) at C:\Users\alper\.julia\packages\Gurobi\dlJep\src\MPB_wrapper.jl:71
  LinearQuadraticModel(!Matched::CbcSolver) at C:\Users\alper\.julia\packages\Cbc\rWU6K\src\MPB_wrapper.jl:33
  ...
in expression starting at C:\Users\alper\Desktop\uc\basicUC.jl:105
#build#108(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::Model) at solvers.jl:358
#build at none:0 [inlined]
#solve#105(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at solvers.jl:168
solve(::Model) at solvers.jl:150
top-level scope at none:0

**Comment by harshangrjn** [comment]
Can you post the problem you are trying to run here (if it's not too big)?

**Comment by asavasci** [comment]
clearconsole()

## D_t : Net load in period t ∈ T, ( MW )
#
D = [700,750,850,950,1000,1100,1150,1200,1300,1400,1450,1500,
     1400,1300,1200,1050,1000,1100,1200,1400,1300,1100,900,800];

## Cost function parameters for 10-unit system
#
a = [1000,970,700,680,450,370,480,660,665,670]; # Fixed cost of running generator g ∈ G, ( $/h )
b = [16.19,17.26,16.60,16.50,19.70,22.26,27.74,25.92,27.27,27.79]; # ( $/MWh)
c = [0.00048,0.00031,0.002,0.00211,0.00398,0.00712,0.00079,0.00413,0.00222,0.00173]; # ( $/MW^2h)

## Maximum and Minimum production limits of generators
#
Pmax = [682.5,682.5,195,195,243,120,127.5,82.5,82.5,82.5]; # ( MW )
Pmin = [225,225,30,30,37.5,30,37.5,15,15,15]; # ( MW )

## Start up and Ramp up rate of generators
#
StartUpRate = [337.5,337.5,45,45,56.25,45,56.25,22.5,22.5,22.5]; # ( MW )
RampUpRate  = [405,405,54,54,67.5,54,67.5,27,27,27]; # ( MW )

## Shut down and Ramp down rate of generators
#
ShutDwnRate = [337.5,337.5,45,45,56.25,45,56.25,22.5,22.5,22.5]; # ( MW )
RampDwnRate = [405,405,54,54,67.5,54,67.5,27,27,27];  # ( MW )

## Minimum up and Minimum down time of generators
#
MinUpTime = [8,8,5,5,6,3,3,1,1,1]; # (h)
MinDwnTime = [8,8,5,5,6,3,3,1,1,1]; # (h)

## Start-up cost of generator
#
StartUpCost = [4500,5000,550,560,900,170,260,30,30,30]; # ( $/h )
ShutDwnCost = zeros(10); # ( $/h )



T = 3; # Number of time periods
G = 10; # Number of generators

## Model and solver decleration
#

using JuMP
using Alpine
using Gurobi, Ipopt


uc = Model()

setsolver(uc, AlpineSolver(nlp_solver=IpoptSolver(print_level=0), mip_solver=GurobiSolver()))


## Problem variables
#
@variable(uc, P[1:G,1:T]) # Production amount of generator g ∈ G in period t ∈ T
@variable(uc, u[1:G,1:T], Bin) # Status of generator g ∈ G in period t ∈ T -- 1 if generator g is ON in period t; 0 otherwise
@variable(uc, y[1:G,1:T], Bin) # Start up decision of generator g ∈ G in period t ∈ T  -- 1 if u[g,(t−1)] = 0 and u[g,t] = 1; 0 otherwise
@variable(uc, z[1:G,1:T], Bin) # Shut down decision of generator g ∈ G in period t ∈ T -- 1 if u[g,(t−1)] = 1 and uit = 0; 0 otherwise

## Problem constraints
#
@constraint(uc, Power_Balance_Constraint[t=1:T],
                sum(P[:,t]) == D[t] )


@constraint(uc, GenerationLimitsMax_Constraint[t=1:T,g=1:G],
                P[g,t] <= Pmax[g]*u[g,t] )


@constraint(uc, GenerationLimitsMin_Constraint[t=1:T,g=1:G],
                Pmin[g]*u[g,t] <= P[g,t] )


@constraint(uc, MinUpTime_Constraint[g=1:G, t=2:T, tau=t+1:min(t+MinUpTime[g],T)],
                u[g,t] - u[g,t-1] <= u[g,tau])

@constraint(uc, MinDwnTime_Constraint[g=1:G, t=2:T, tau=t+1:min(t+MinDwnTime[g],T)],
                u[g,t-1] - u[g,t] <= 1 - u[g,tau])

@constraint(uc, StartUp_Constraint[g=1:G, t=2:T],
                u[g,t] - u[g,t-1] <= y[g,t])

@constraint(uc, ShutDwn_Constraint[g=1:G, t=2:T],
                u[g,t-1] - u[g,t] <= z[g,t])

@constraint(uc, RampStartUp_Constraint[g=1:G, t=2:T],
                P[g,t] - P[g,t-1] <= StartUpRate[g]*y[g,t] + RampUpRate[g]*u[g,t-1])

@constraint(uc, RampShutDwn_Constraint[g=1:G, t=2:T],
                P[g,t-1] - P[g,t] <= ShutDwnRate[g]*z[g,t] + RampDwnRate[g]*u[g,t])



## Objective Function
#
@objective(uc, Min, sum(a[g]*u[g,t] + b[g]*P[g,t] + c[g]*P[g,t]*P[g,t] for g=1:G, t=1:T ))

status = solve(uc)

**Comment by harshangrjn** [comment]
Looks like your problem is just a MIQP with linear constraints, which is convex. You should be able to solve it directly using Gurobi/CPLEX. Alpine is meant for solving nonconvex programs. In any case, use @NLobjective (as your objective is quadratic) in your problem and Alpine will still try to solve it.

**Comment by asavasci** [comment]
When I specify @NLobjective I am getting following error

ERROR: LoadError: Problem is a MINLP and no MINLP local solver given; use minlp_solver to specify a MINLP local solver
Stacktrace:
 [1] loadproblem!(::Alpine.AlpineNonlinearModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at C:\Users\alper\.julia\packages\Alpine\k3g7z\src\solver.jl:680
 [2] _buildInternalModel_nlp(::Model, ::JuMP.ProblemTraits) at C:\Users\alper\.julia\packages\JuMP\I7whV\src\nlp.jl:1244
 [3] #build#108(::


ERROR: LoadError: Problem is a MINLP and no MINLP local solver given; use minlp_solver to specify a MINLP local solver
Stacktrace:
 [1] loadproblem!(::Alpine.AlpineNonlinearModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at C:\Users\alper\.julia\packages\Alpine\k3g7z\src\solver.jl:680
 [2] _buildInternalModel_nlp(::Model, ::JuMP.ProblemTraits) at C:\Users\alper\.julia\packages\JuMP\I7whV\src\nlp.jl:1244
 [3] #build#108(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::Model) at C:\Users\alper\.julia\packages\JuMP\I7whV\src\solvers.jl:305
 [4] #build at .\none:0 [inlined]
 [5] #solve#105(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at C:\Users\alper\.julia\packages\JuMP\I7whV\src\solvers.jl:168
 [6] solve(::Model) at C:\Users\alper\.julia\packages\JuMP\I7whV\src\solvers.jl:150
 [7] top-level scope at none:0
in expression starting at C:\Users\alper\Desktop\uc\basicUC.jl:102

**Comment by harshangrjn** [comment]
If you use `setsolver(uc, GurobiSolver())` instead of Alpine, you will be able to solve your problem. 

If you have an MIQP (form of MINLP), you will need to provide a `minlp_solver` instead of `nlp_solver`. You can use this as the local MINLP solver or Alpine: https://github.com/lanl-ansi/Juniper.jl

**Comment by asavasci** [comment]
Okay. Thanks for your time

**Comment by harshangrjn** [comment]
Closing the issue for now. If you encounter anything else, feel free to open this back.

**Comment by asavasci** [comment]
Having issues with Juniper solver call. I slightly changed my problem into an MINLP, but JuniperSolver() seems not supported by JuMP 0.18. Could you please verify it?
[basic_UC_v2.txt](https://github.com/lanl-ansi/Alpine.jl/files/3697710/basic_UC_v2.txt)

**Comment by Wikunia** [comment]
I currently can't test it easily as I have the newest versions installed but I think you simply have to use `JuniperSolver(IpoptSolver(print_level=0))` instead of just `JuniperSolver` as Juniper needs a nlp solver. You're probably using v0.3.0 of Juniper which is described here:
https://lanl-ansi.github.io/Juniper.jl/v0.3/

**Comment by asavasci** [comment]
I tested Juniper on separate example given here : [https://lanl-ansi.github.io/Juniper.jl/v0.3/](url). Juniper is working. However, I am getting the following error 

LoadError: Unsupported MINLP local solver Juniper.JuniperSolverObj(IpoptSolver(Tuple[(:print_level, 0)]), log_levels                          : Symbol[:Options, :Table, :Info]
atol                                : 1.0e-6
num_resolve_root_relaxation         : 3
branch_strategy                     : StrongPseudoCost
gain_mu                             : 0.167
strong_branching_perc               : 100.0
strong_branching_nsteps             : 1
strong_branching_approx_time_limit  : 100.0
strong_restart                      : true
reliability_branching_threshold     : 5
reliability_branching_perc          : 25.0
incumbent_constr                    : false
obj_epsilon                         : 0.0
time_limit                          : Inf
mip_gap                             : 0.0001
best_obj_stop                       : NaN
solution_limit                      : 0
all_solutions                       : false
list_of_solutions                   : false
processors                          : 1
traverse_strategy                   : BFS
feasibility_pump                    : false
feasibility_pump_time_limit         : 60.0
feasibility_pump_tolerance_counter  : 5
tabu_list_length                    : 30
num_resolve_nlp_feasibility_pump    : 1
mip_solver                          : NA
force_parallel                      : false
debug                               : false
debug_write                         : false
debug_file_path                     : debug.json
fixed_gain_mu                       : false
); use a Alpine-supported MINLP local solver
in expression starting at C:\Users\alper\Desktop\uc\Deterministic_UC.jl:103
error(::String) at error.jl:33
#fetch_minlp_solver_identifier#338(::String, ::Function, ::Alpine.AlpineNonlinearModel) at utility.jl:794
fetch_minlp_solver_identifier at utility.jl:771 [inlined]
loadproblem!(::Alpine.AlpineNonlinearModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at solver.jl:722
_buildInternalModel_nlp(::Model, ::JuMP.ProblemTraits) at nlp.jl:1244
#build#108(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::Model) at solvers.jl:305
#build at none:0 [inlined]
#solve#105(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at solvers.jl:168
solve(::Model) at solvers.jl:150
top-level scope at none:0
