### ISSUE TITLE
Travis and Documeter Maintenance

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Alpine.jl#144]
See, https://github.com/lanl-ansi/PowerModels.jl/commit/1eb1500313ba6cfeb8e3c5e7f22f76142242d7aa and https://github.com/lanl-ansi/PowerModels.jl/commit/d1ab450bb68fdbdc687564be3651c5ddf420ab72

**Comment by harshangrjn** [comment]
Fixed this in v0.1.16.
