### ISSUE TITLE
bound propagation buggy

### ISSUE THREAD

**Issue by tweisser** [lanl-ansi/Alpine.jl#147]
I think the test [here](https://github.com/lanl-ansi/Alpine.jl/blob/64b751a50e758e6ef5da0b8652ed2cdb1d12bcc1/src/bounds.jl#L147) should be against `m.l_var_tight` in order to stop, when the upper bound is smaller than the lower bound.

**Comment by harshangrjn** [comment]
Perfect! This needs to be fixed. Will get it fixed for your example problem.

**Comment by harshangrjn** [comment]
@tweisser Do you want to send a PR for this? ;)
