### ISSUE TITLE
Unnecessary use of eval in source code

### ISSUE THREAD

**Issue by julbinb** [lanl-ansi/Alpine.jl#153]
[This use of `eval`](https://github.com/lanl-ansi/Alpine.jl/blob/72814dd2343408df030024fc0f656c662b225f94/src/algorithm.jl#L344) does not do anything useful:

```julia
if isa(m.disc_var_pick, Function)
      eval(m.disc_var_pick)(m)
```

It's similar to writing `eval(3)` instead of `3`. Because `m.disc_var_pick` is already a function, it would be faster to call it directly, `m.disc_var_pick(m)`. For comparison, here is an example with `rand`:

```julia
julia> using BenchmarkTools

julia> @btime rand()
  4.558 ns (0 allocations: 0 bytes)

julia> @btime eval(rand)()
  67.705 ns (1 allocation: 16 bytes)
```

**Comment by harshangrjn** [comment]
@julbinb Thanks for your helpful suggestions. I have updated the code and eliminated the usage of evals as much as possible. If you get chance to review the the recent release (v0.2.0) and see if this needs any more changes, let me know and I shall get them fixed. If not, will close the issue.

**Comment by julbinb** [comment]
@harshangrjn you are welcome! I will try to take a look over the next week.

**Comment by julbinb** [comment]
I see a couple of uses of `eval` that might or might not have a similar issue, e.g. [here](https://github.com/lanl-ansi/Alpine.jl/blob/50a111e41355530c068a7379ba62b12529fc1915/src/nlexpr.jl#L197) or [here](https://github.com/lanl-ansi/Alpine.jl/blob/bce6d263b387c08de8d8bd9695515e8dd82aa20e/src/utility.jl#L83). If what `convertor[..]` contains is already a function (i.e. a value for which `typeof` returns `Function`), it would be unnecessary to call `eval`. But I didn't look at the code close enough to figure that out.

**Comment by harshangrjn** [comment]
@julbinb Thanks! Will look into it and make changes where necessary.

**Comment by harshangrjn** [comment]
Most of the unnecessary `eval()` functions have been removed in this update.
