### ISSUE TITLE
Support for Juniper's feasibility status

### ISSUE THREAD

**Issue by harshangrjn** [lanl-ansi/Alpine.jl#157]
Alpine throws an error when Juniper.jl returns "ALMOST_LOCALLY_SOLVED". Add this option in https://github.com/lanl-ansi/Alpine.jl/blob/1dddbbdc0f6da7eb5e58bdad00ddd86af1ce0ddb/src/algorithm.jl#L7

@ccoffrin Any other useful/acceptable status which may need to be added to this list? (Not able to tag Ole here for some reason).

**Comment by ccoffrin** [comment]
I think you have it covered.  You can have a look at these common cases, https://jump.dev/MathOptInterface.jl/dev/apimanual/#Common-status-situations-1

**Comment by harshangrjn** [comment]
Great! This list helps.
