### ISSUE TITLE
Alpine checks solver name - Why?

### ISSUE THREAD

**Issue by freemin7** [lanl-ansi/Alpine.jl#178]
Why does Alpine check for the string of solvers and throws an error if it is a string it doesn't like? 
What is trying to be accomplished?
I would be interested in finding a better solution.

[Relevant code here.](https://github.com/lanl-ansi/Alpine.jl/blob/b058efb49cce0530bb27fb93d943ea28f1f30a7d/src/utility.jl#L482)

**Comment by ccoffrin** [comment]
As I recall, this is from an older generation of JuMP when it was not possible if a given solver supports a specific type of problem.  I believe this check was trying to check that the given solver supports the "NLPBlock".  Presumably now, post MOI, there is a better way to accomplish this check.

**Comment by blegat** [comment]
I think this is used to set solver-specific solver attributes in case the solver is Ipopt

**Comment by harshangrjn** [comment]
This is done to access a few solver-specific attributes of Gurobi (soln pool, etc). But this can be made better for other nlp/minlp solvers as it is mainly used for logging purposes.

**Comment by harshangrjn** [comment]
v0.4.3 addresses this issue.
