### ISSUE TITLE
PrimalStatus not defined

### ISSUE THREAD

**Issue by blegat** [lanl-ansi/Alpine.jl#187]
When using `JuMP.solution_summary` with Alpine, the user gets
```
ERROR: LoadError: ArgumentError: ModelLike of type Alpine.Optimizer does not support accessing the attribute MathOptInterface.PrimalStatus(1)
```

**Comment by odow** [comment]
I think this is really just "fix the MathOptInterface wrapper" https://github.com/lanl-ansi/Alpine.jl/issues/152.

Blocked by the fact I need permission to run CI and https://github.com/lanl-ansi/Alpine.jl/pull/188
