### ISSUE TITLE
Fix cycling detected in tests

### ISSUE THREAD

**Issue by odow** [lanl-ansi/Alpine.jl#190]
I left quite a few TODOs in the tests:
https://github.com/lanl-ansi/Alpine.jl/blob/ecf084c86d78fbbf3088630dc5e7366354d11a60/test/test_algorithm.jl#L153-L155
We should investigate and/or fix.

**Comment by harshangrjn** [comment]
@odow This is an issue with Pavito and not Alpine? If I run Pavito with Gurobi/CPLEX as underlying MIP solver instead of Cbc, the mixed-integer cycling doesn't appear in Pavito.

**Comment by odow** [comment]
the issue is in Pavito. But the problem is that these tests are flakey, so they should probably be changed to not encounter Pavito's cycling.

**Comment by harshangrjn** [comment]
Agreed! Was going to update some of these tests in the PR.

**Comment by harshangrjn** [comment]
@odow From my observations, when an NLP exhibits multiple symmetric arg mins for the global minimum (like (-1,1), (1,1), (1,-1), (-1,-1)), Pavito seems to get into the MI cycling issue when Cbc and Ipopt are the underlying solvers. Of course, this doesn't happen with Gurobi is it's underlying solver. Although, I updated the unit tests in Alpine to make them a bit more meaningful and break this solution symmetry. Let me know if this needs more attention here.
