### ISSUE TITLE
Alpine major refactor

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/Alpine.jl#215]
@harshangrjn @sujeevraja  

This issue is to keep track of the planned refactor and new features for Alpine.jl . To complete this refactor, the following things need to be taken care of. This can be tagged as milestone for v1.0 of Alpine.jl conforming with all other JuMP-based solvers. 

- [x] Migrate all Piecewise Relaxations and LP relaxations to PolyhedralRelaxations.jl 
- - [x] Univariate functions 
- - [x] McCormick Relaxation
- - [x] Multilinear terms (only SOS-2 based) relaxations
- - [x] Linking constraints for multilinear terms
- - [x] Partition Refinement Schemes
- - [x] Add unit tests for all the above
- - [ ] Document all relaxations
- - [ ] Tag new release of https://github.com/sujeevraja/PolyhedralRelaxations.jl with all the above features 
- [ ] Create an OBBT.jl package which will just perform Optimization-Based Bound Tightening 
- [ ] Create a package/module withing Alpine to isolate non-linear terms, create auxiliary variables and perform book-keeping (this is already a part of Alpine, only need to clean up) - Parsing module 
- [ ] Create a package/module for convexity detection of constraints and objective - ConvexityDetection module 
- [ ] Use the above two modules and PolyhedralRelaxations.jl to implement the  relaxations within Alpine.
- [ ] Benchmark with MINLPLib.

**Comment by sujeevraja** [comment]
Plan looks great.

**Comment by harshangrjn** [comment]
@kaarthiksundar Thanks for making these decisions independently without having sufficient discussions with relevant folks around. I am not clear on why any of these features need to be moved out of Alpine. Although I agree with a major refactoring for Alpine, in my opinion, cleaning up Alpine and having dedicated modules within Alpine to perform any of these features independently (very much like how PR.jl does) should be ideal. Very much in lines with https://github.com/networkx where all the refactoring of documentation and only redundant functionalities get separated out from Alpine. In fact, now that you think PR.jl is working well, I would suggest we should:
1) Bring in the functionalities of piecewise univariate functions with incremental formulations (like trigonometric functions) into Alpine 
2) Implement multilinear relaxations with linking constraints (which exists, but needs a clean-up) within Alpine, and be able to invoke of these relaxations independently without any parsing of JuMP model. A function which just takes a JuMP model, set of variables which needs to be partitioned, etc) 
3) Apply OBBT only if necessary within Alpine, and invoke all the above and more relaxation models. 
4) Apply convexity recognition, potentially as an Alpine model and then invoke the remaining functionalities. 

If we concur on the above suggestions, of course I am also open to suggestions for brining more functionalities (which are necessary), I will be happy to discuss with you guys. Else, we can close this issue.

**Comment by kaarthiksundar** [comment]
Great then. Let us keep this issue open, so that we can keep track of progress. This hopefully should be done in a year's time depending on time bandwidth. As things start combining, I will send a Pull Request. We will also modify tasks as we make progress.

**Comment by harshangrjn** [comment]
Closing it for now, but we can always re-open considering how progress happens.
