### ISSUE TITLE
Quadratic Constraints and Functions are passed to MILP solvers.

### ISSUE THREAD

**Issue by felipemarkson** [lanl-ansi/Alpine.jl#220]
When you are using an pure MILP solver, like `Cbc` or  `HiGHS`, `Alpine` is not applying the appropriate relaxations on quadratic functions.

The same issue is not found on `Gurobi` because `Gurobi` can handle with quadratic constraints.

Bellow you can see a minimal reproducible example:

```julia
using JuMP
using Cbc, Ipopt, Alpine

# MIP optimizer
cbc = optimizer_with_attributes(
    Cbc.Optimizer,
    MOI.Silent() => true)

# NLP optimizer
ipopt = optimizer_with_attributes(Ipopt.Optimizer,
    MOI.Silent() => true,
    "sb" => "yes",
    "max_iter" => 9999)

# Global optimizer
alpine = optimizer_with_attributes(Alpine.Optimizer,
    "nlp_solver" => ipopt,
    "mip_solver" => cbc)


model = Model(alpine)
@variable(model, x ≥ 0)
@NLconstraint(model, x^2 ≥ 1)
@NLobjective(model, Min, x^3)

optimize!(model)

```

Here you can see the Error message:
![image](https://user-images.githubusercontent.com/47871564/192584120-3aeea056-7945-468c-92ac-a3181ae4c3ba.png)

**Comment by felipemarkson** [comment]
Thanks!

So, I suggest remove MILP solvers from the documentation.
Or warning the user about this issue on the documentation as well.

**Comment by harshangrjn** [comment]
@felipemarkson I agree that the docs should clearly mention this. Regarding the `x^2 >= 1` constraint, note that Alpine reformulates this into a convex constraint and applies partitioning to capture the non-convex side of the constraint. This reformulated convex MIP shouldn't have any issue to be be able to solve in Pavito.

**Comment by felipemarkson** [comment]
Sorry I was my mistake!

You are right! Using Pavito instead of an pure `MILP` should work

**Comment by harshangrjn** [comment]
Here is the script to run your NLP using Pavito and Ipopt within Alpine, which runs fine. 

```
using Alpine
using JuMP
using Ipopt
using Pavito
using HiGHS

function get_highs()
    return JuMP.optimizer_with_attributes(
        HiGHS.Optimizer,
        "log_to_console" => false,
    )
end

function get_pavito(mip_solver, cont_solver)
    return optimizer_with_attributes(
        Pavito.Optimizer,
        MOI.Silent() => true,
        "mip_solver" => mip_solver,
        "cont_solver" => cont_solver
    )
end

function get_ipopt()
    return optimizer_with_attributes(
        Ipopt.Optimizer,
        MOI.Silent() => true,
        "sb" => "yes",
    )
end

mip_solver = get_pavito(get_highs(), get_ipopt())
nlp_solver = get_ipopt()

alpine = JuMP.optimizer_with_attributes(
    Alpine.Optimizer,
    "nlp_solver" => nlp_solver,
    "mip_solver" => mip_solver,
    "presolve_bt" => true,
    "apply_partitioning" => true,
)

model = Model(alpine)
@variable(model, 0 <= x <= 10)
@NLconstraint(model, x^2 ≥ 1)
@NLobjective(model, Min, x^3)

JuMP.optimize!(model)
```

**Comment by felipemarkson** [comment]
Thanks! this model works here!

Should I close this issue? Or is it  a documentation issue?

**Comment by harshangrjn** [comment]
Feel free to close it. Have made note of docs update.
