### ISSUE TITLE
Example problems don't define variables as integers

### ISSUE THREAD

**Issue by Vaibhavdixit02** [lanl-ansi/Alpine.jl#231]
I was looking at the (great collection of) examples provided in this package and noticed that other than binary variables, other variable definitions don't seem to have the domain specified (integer). Curious if that's just an oversight or if I am missing something?

**Comment by harshangrjn** [comment]
@Vaibhavdixit02  Could you point to the exact example where you observe this issue?

**Comment by Vaibhavdixit02** [comment]
Actually, I might have been misunderstanding the layout. So looks like there are some continuous non-linear examples in the https://github.com/lanl-ansi/Alpine.jl/tree/master/examples/MINLPs folder like this file https://github.com/lanl-ansi/Alpine.jl/blob/master/examples/MINLPs/castro.jl which confused me. I can see that integer.jl has MINLP problems with `int` specified in the `@variables` definition so that clarified the confusion for me.
