### ISSUE TITLE
Falsely declared support for MOI.Integer

### ISSUE THREAD

**Issue by odow** [lanl-ansi/Alpine.jl#244]
This should be `false`:

https://github.com/lanl-ansi/Alpine.jl/blob/a1849ddf464a9a567eeb9bb7c9707c77bbccbf88/src/MOI_wrapper/MOI_wrapper.jl#L325-L331

See https://github.com/jump-dev/MathOptInterface.jl/issues/2517

**Comment by LebedevRI** [comment]
But won't that also forbid `Bin`ary  variables?
