### ISSUE TITLE
Validating domain reduction methods' correctness

### ISSUE THREAD

**Issue by jac0320** [lanl-ansi/Alpine.jl#59]
As domain reduction weights more in the algorithm, it is necessary to have an efficient method to validate a variable's bound contraction implementation. Like we test strong duality during Bender's implementation,   can there be a numerical method to validate any algorithm's resulting bounds?

For example, with the linear following constraints,
0.1 <= x[i] <= 3, i=1..3
x[1] + x[2] + x[3] <= 3
It is clear that  0.1 <= x[i] <= 2.8, which can be concluded using domain reduction schemes.

Say f(x) => LB(x) & UB(x), where f(x) only focus on linear constraints, how should I validate the correctness of f(x) given existing problem information.

**Comment by kaarthiksundar** [comment]
Closing https://github.com/lanl-ansi/Alpine.jl/issues/101
