### ISSUE TITLE
request presolve algorithm feature with convex constraint detection is on

### ISSUE THREAD

**Issue by jac0320** [lanl-ansi/Alpine.jl#79]
@kaarthiksundar asked to do this

Include a solver option called is_convex::Bool (default set to false). 

If is_convex is true - then do to the following
1. Allow for BT iff bound tightening option is set to true and then do one local solve to get the optimal solution. 
2. If BT is set to false then just do one local solve to get the optimal solution. 

In this way our solver can handle convex problems if the user can let us know the problem is convex.

**Comment by kaarthiksundar** [comment]
https://github.com/lanl-ansi/Alpine.jl/issues/101
