### ISSUE TITLE
Generate convex relaxations for nonconvex MINLPs

### ISSUE THREAD

**Issue by CanLi1** [lanl-ansi/Alpine.jl#86]
Hi,

I have a question regarding using the code of POD.jl. Suppose I have a nonconvex MINLP written as a JuMP model. I wonder if I can use some piece of the code to generate a convex relaxation for this nonconvex MINLP and return the convex relaxation as a JuMP or MathProgBase model. It would be great if this can be done. Other convex relaxations may be implemented to compare with the existing ones. It seems that the operator.jl file can detect nonconvexity. Is there a function that will return the convex relaxation? 

Thanks you very much!

Best regards,
Can

**Comment by kaarthiksundar** [comment]
Yes, this can be done - but not in the way you are mentioning. POD does create a convex relaxation model underneath. It is just that, we have not implemented functions where the user can get a handle on that model. This is feature that we will work on in some time. We are in the process or making bug fixes and releasing a version 0.1. After that, I should have some time to implement the feature that you ask for.

**Comment by harshangrjn** [comment]
@CanLi1 For your non convex MINLP, are you looking at variants of your piecewise relaxations (like the way POD.jl iterates) or just the basic relaxation of the MINLP (which is our 0th iteration)?

**Comment by CanLi1** [comment]
@harshangrjn It would be great if the piecewise relaxations can be accessible.
