### ISSUE TITLE
Debug Flag

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/Alpine.jl#95]
A good logger will support debugging messages, that would be preferable to the `ALPINE_DEBUG` flag.

**Comment by kaarthiksundar** [comment]
What is your opinion on using using Memento?

**Comment by ccoffrin** [comment]
Seems like the best option until there is a clear example of how to use the
built in logger.

**Comment by kaarthiksundar** [comment]
https://github.com/lanl-ansi/Alpine.jl/issues/101
