### ISSUE TITLE
Cplex solver with Alpine 

### ISSUE THREAD

**Issue by krishpat** [lanl-ansi/Alpine.jl#97]
Alpine looks interesting and I am trying to use it for some non convex problems. But I get this error when I run the following code. Is this because Alpine doesn't support CPLEX? 

Code:
```
m = Model(solver=AlpineSolver(nlp_solver = IpoptSolver(), mip_solver=CplexSolver()))

@variable(m, -1 <= x[1:2] <= 1)

@NLobjective(m, Min, (x[1]*x[2]) + x[2])
solve(m)
```
Error:
```
ERROR: LoadError: Unsupported MIP solver CplexSolver(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}()); use a Alpine-supported MIP solver
```

**Comment by kaarthiksundar** [comment]
The bug is fixed. Please update Alpine and then try.

**Comment by krishpat** [comment]
It works now. Thanks.

**Comment by krishpat** [comment]
Now I am having another issue. Running the above code with Gurobi as the MIP solver is giving an error. Is this a similar issue as CPLEX?

**Comment by harshangrjn** [comment]
@krishpat We are aware of this issue. Will let you know once fixed.

**Comment by kaarthiksundar** [comment]
Closing. See 
https://github.com/lanl-ansi/Alpine.jl/issues/101
