### ISSUE TITLE
What's required for other solvers to be used?

### ISSUE THREAD

**Issue by matbesancon** [lanl-ansi/Alpine.jl#98]
I want to compare Alpine + SCIP with SCIP only for a MIP with bilinear terms. What would be required for new solvers to be added?

**Comment by kaarthiksundar** [comment]
SCIP itself is a global solver. What do you mean when you say Alpine + SCIP

**Comment by matbesancon** [comment]
SCIP solves mixed-integer linear problems (there is a non-linear part but I intended to use it for its MILP)

**Comment by harshangrjn** [comment]
As of now, Alpine does not support SCIP to be used as the MIP solver. You can use CPLEX, Gurobi or CBC.  Alpine's performance is the best when CPLEX or Gurobi is used.

**Comment by krishpat** [comment]
I had a similar question on how to use SCIP as the MIP solver for Alpine as it is somewhat an open source and probably better than CBC.

**Comment by kaarthiksundar** [comment]
Closing. 
https://github.com/lanl-ansi/Alpine.jl/issues/101
