### ISSUE TITLE
Invalid coefficient -Inf error

### ISSUE THREAD

**Issue by krishpat** [lanl-ansi/Alpine.jl#99]
I am trying to use Alpine to globally optimize this NLP

```
m = Model(solver=AlpineSolver(nlp_solver = IpoptSolver(), mip_solver = CplexSolver()))

@variable(m, x[1:2] >= 0)
@NLobjective(m, Max, (x[1]-1)^2 + x[2]^2)
@NLconstraint(m, x[1]^2 + 6*x[2] - 36 <= 0)
@NLconstraint(m, -4*x[1] + x[2]^2 - 2*x[2] <= 0)
solve(m)
```
Alpine complains saying "ERROR: LoadError: Invalid coefficient -Inf on variable A2[1]". But there is also a warning initially saying 
"Inf bound detected on 4 variables. Initialize with value -/+10000.0. This may affect global optimality and performance."

Ipopt seems to return a local optimal point but Alpine gets stuck in the presolve. 

Is there a fix for this issue?

**Comment by harshangrjn** [comment]
@krishpat: There is a bug in Alpine in the way upper bounds are assigned to the variables which are not bounded above. We need to fix that. 

But a quick fix for this issue is by initializing the variables with a large UB. Say, 
```
@variable(m, 0 <= x[1:2] <= 10000)
```
By doing so, Alpine converges to the Global optimum. Here is the log of tightened bounds: 
```
 VAR 1 BOUND contracted 100.0% |0.0 --> | 2.9317 - 6.0 | <-- 10000.0 |
 VAR 2 BOUND contracted 100.0% |0.0 --> | 0.0 - 4.5675 | <-- 10000.0 |
 VAR 3 BOUND contracted 100.0% |-1.0 --> | 1.9317 - 5.0 | <-- 9999.0 |
```
And the iterations of Alpine: 
```
 | NLP           | MIP           || Objective     | Bound         | GAP (%)       | CLOCK         | | Iter   
 | 24.5935       | 25.0          || 24.5935       | 25.0          | 1.65273       | 5.11s         | | 1
 | 20.3208       | 25.0          || 24.5935       | 25.0          | 1.65273       | 5.13s         | | 2
 | 25.0          | 25.0          || 25.0          | 25.0          | 0.0           | 5.13s         | | finish
```
As you can see, Ipopt finds a local optimum but Alpine finds the global optimum. 

P.S. Thanks for sharing this instance. It is interesting that the local optimum value (found by Ipopt) is quite close to the global optimum but the argmax values are quite far away.

**Comment by krishpat** [comment]
@harshangrjn Thanks for the fix. I also didn't realize the global optimum would be at (6,0). 

Doesn't this warning "Initialize with value -/+10000.0" imply that Alpine has automatically assigned these upper bounds to the variables. 

On a different note, does Alpine recognize that only the objective is non-convex but not the constraints?

**Comment by harshangrjn** [comment]
On your question on convexity check, Alpine currently does not recognize your constraints as convex. The only convex recognitions are for constraints of the standard quadratic and conic form, which can be seen in this file: https://github.com/lanl-ansi/Alpine.jl/blob/fe9b7c7f934c39f008f00d25ab43642cb7a94393/src/operators.jl#L1229

**Comment by krishpat** [comment]
Not related to this thread but was curious. Does Alpine support functions of type f(x,y) = x/y over a rectangle in the positive orthant?

**Comment by harshangrjn** [comment]
@krishpat Not yet! It is on our to-do list.

**Comment by ccoffrin** [comment]
Usually you can re-formulate constraints of the form `z = x/y` into `y*z = x`.  This one of the reasons `x/y` has not yet been a high priority.

**Comment by kaarthiksundar** [comment]
Closing. 
https://github.com/lanl-ansi/Alpine.jl/issues/101
